### ISSUE TITLE
Strange rendering issues when client is using Fabric with performance mods.

### ISSUE THREAD

**Issue by TheDeafCreeper** [LOOHP/Limbo#5] opened 2020-12-02 01:18 UTC
Typically this is something that would be a client side issue, however this rendering issue only happens on the limbo server, I could not find any instances of it on Paper, Tuinity, or Vanilla servers.
Basically some chunks (almost exclusively to the north and west) fail to render, with some chunks (Typically near the southwest boundary and north east boundary) only rendering after being updated.

Client Version: Fabric 0.10.6 (1.16.4) {Containing mods: Lithium, Phosphor, and Sodium
Server Version: Limbo 0.3.6-ALPHA-1.16.4
![2020-12-01_19 10 56](https://user-images.githubusercontent.com/34897909/100815500-b6bb2480-3409-11eb-9b92-bfcdb95e523f.png)
![2020-12-01_19 13 03](https://user-images.githubusercontent.com/34897909/100815503-b9b61500-3409-11eb-96be-589ff1dc9025.png)

**Comment by LOOHP** [comment] 2020-12-03 14:56
It might be caused by edge chunks, try having your schematic with an extra empty chunk on each side to see if that help

**Comment by TheDeafCreeper** [comment] 2020-12-03 21:57
That fixed it.

**Comment by LOOHP** [comment] 2020-12-05 02:57
Awesome, I might add extra chunks around schemes by default in the future, Closing this for now.

**Closed by LOOHP** 2020-12-05 02:57 UTC
